import Head from "next/head";
import { PostCard, Categories, PostWidget } from "../components";

export default function Home() {
  const posts = [
    { title: "React Testing", excerpt: "Learn React Testin" },
    { title: "React with Tailwind", excerpt: "Learn React with Tailwind" },
  ];

  return (
    <div className="container mx-auto px-10 mb-8 bg-gray-100">
      <Head>
        <title>CMS Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post, index) => (
            <PostCard key={post.title} post={post} />
          ))}
        </div>
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8">
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>
    </div>
  );
}
